pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t igc-admin:latest .'
            }
        }
        stage('Push to ECR') {
            steps {
                sh 'aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 300759383064.dkr.ecr.us-east-2.amazonaws.com'
                sh 'docker tag igc-admin:latest 300759383064.dkr.ecr.us-east-2.amazonaws.com/igc-admin:latest'
                sh 'docker push 300759383064.dkr.ecr.us-east-2.amazonaws.com/igc-admin:latest'
            }
        }
        stage('Test server deployment') {
            steps {
                sshagent(['contabo-dev']) {
                    sh 'ssh -p2222 -o StrictHostKeyChecking=no -l root 164.68.113.179 ./igc_admin.sh'
                }
            }
        }
    }
}

